### ISSUE TITLE
Issue with popgraph

### ISSUE THREAD

**Issue by tanyasarkinjain** [dyerlab/gstudio#17]
SAGraphMsat2 <- popgraph(x = SADataMsat2.mv, groups = pops2)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'diag': supply both 'x' and 'y' or a matrix-like 'x'
In addition: Warning messages:
In addition: Warning messages:
1: In popgraph(x = SADataMsat2.mv, groups = pops2) :
  You have strata ( Pop-11, Pop-12, Pop-13, Pop-5 ) that have fewer than 4 individuals. This analysis needs to have a good estimate of within stratum variance.
2: In popgraph(x = SADataMsat2.mv, groups = pops2) :
  1 variables are collinear and being dropped from the discriminant rotation.

I understand the warning message, however I am confused as to why I am getting the error I am inputting a matrix. I do not get that error message when I use a different set of populations  (instead of pops2) that correspond to a different division of the data than what was specified in the .gen file for this analysis.

**Comment by dyerlab** [comment]
Drop the sites with N<4 and try again.
--
Rodney J. Dyer, PhD
Director, Center for Environmental Studies
<https://ces.vcu.edu/>
Virginia Commonwealth University
http://dyerlab.com

**Comment by tanyasarkinjain** [comment]
Thank you! That worked.

**Comment by dyerlab** [comment]
Yes, the issue is that the estimation of a pop graph requires that you have a good idea of the within site genetic variance.  I put an artificial limit of 4 individuals to make a site as a lower boundary to ensure that we are not going to be dividing by zero at some point…


Rodney Dyer, PhD
Professor, Director
Center for Environmental Studies <https://ces.vcu.edu/>
Virginia Commonwealth University <https://vcu.edu/>
***@***.*** ***@***.***>
dyerlab.org <https://dyerlab.org/>
